#!/bin/bash

# Check if the user provided exactly one argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {install|uninstall|reload}"
    exit 1
fi

# Use a case statement to handle the options
case $1 in
    install)
        # Symlink everything in 'home' directly to ~
        stow -t ~ home

        # Symlink everything in 'config' to ~/.config
        stow -t ~/.config config
        echo "Created symlinks from home/ to ~/ and config/ to ~/.config"
        ;;
    uninstall)
        # Remove symlinks in ~ created from 'home'
        stow -t ~ -D home

        # Remove symlinks in ~/.config created from 'config'
        stow -t ~/.config -D config
        echo "Removed symlinks from home/ and config"
        ;;
    reload)
        # Reload symlinks for ~ and ~/.config
        stow -t ~ -D home
        stow -t ~ home

        stow -t ~/.config -D config
        stow -t ~/.config config
        echo "Reloaded symlinks for home/ and config"
        ;;
    *)
        echo "Invalid option: $1"
        echo "Usage: $0 {install|uninstall|reload}"
        exit 1
        ;;
esac

